name: packonix               # The name of your Snap
base: core22
version: '1.0.0'             # The version of your app
summary: A Go-based app      # A short summary of the app
description: |
  A detailed description of your Go application.
grade: stable                # The grade of the Snap (can be stable, candidate, beta, or edge)
confinement: classic          # Use classic confinement instead of strict

apps:
  packonix:
    command: packonix     # The command to run your application (can be a relative path to the binary)

parts:
  packonix:
    plugin: go                # Using the Go plugin to build the application
    source: https://github.com/thehavays/packonix  # GitHub repository URL
    build-packages:
      - build-essential
      - golang-go
    stage-packages:
      - libgo1.18             # Add other dependencies needed for your app

    # Build the binary directly from the Go project, using go.mod to handle dependencies
    override-build: |
      go build -o $SNAPCRAFT_PART_INSTALL/packonix main.go shellapps.go
