name: packonix               # The name of your Snap
base: core22
version: '0.0.1'             # The version of your app
summary: A Go-based app      # A short summary of the app
description: |
  A detailed description of your Go application.
grade: stable                # The grade of the Snap (can be stable, candidate, beta, or edge)
confinement: classic          # Use classic confinement instead of strict
architectures:
  - amd64
  - arm64

apps:
  packonix:
    command: packonix     # The command to run your application (can be a relative path to the binary)

parts:
  packonix:
    plugin: go                # Using the Go plugin to build the application
    source: git+https://github.com/thehavays/packonix.git
    source-type: git
